name: Build Project

on:
  push:
    branches: [main, develop]
  # pull_request:
  #   types: [opened]

jobs:
  # jobs name (any)
  install_dependency:
    # OS from virtual machine GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Copy repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck

  build:
    # depends on install_dependency job
    needs: install_dependency
    runs-on: ubuntu-latest
    steps:
      - name: Copy repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install deps
        run: npm ci

      - name: Build project
        run: npm run build
