name: Build Project

on:
  push:
  # pull_request:
  #   types: [opened]

jobs:
  # jobs name (any)
  install-dependence:
    # OS from virtual machine GitHub
    runs-on: windows-latest
    steps:
      - name: copy repo
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: success message
        run: echo "Dependence install successfully"
